# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t07xwQiAlAzVmFrgiMOWKM4sRmFDmrQS
"""

!sudo apt install tesseract-ocr

!pip install pytesseract

import pytesseract
import shutil
import os
import random
try:
    from PIL import Image
except ImportError:
    import Image

from google.colab import files

uploaded = files.upload()

extractedInformation = pytesseract.image_to_string(Image.open('2.JPG'),lang='fas')

print(extractedInformation)

